helloMessage: "Dev profile"

server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:bankbase
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console.enabled: true     #http://localhost:8080/h2-console

springdoc:
  swagger-ui:
    enabled: true