INSERT INTO "customer_company" ("identifier", "title") VALUES ('01361308', 'Tak Wah Electronic Limited');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('09235168', 'Rice''s Trading LLC');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('06608439', 'Daniels Brothers LLC');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('04982395', 'Lam Kee Logistic Limited');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('07601293', 'Catherine Consultants Inc.');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('06723187', 'Elaine Trading Inc.');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('05393596', 'Chen Kee Company Limited');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('09584280', 'Rui Company Limited');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('00250443', 'Suk Yee Limited');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('01372113', 'Fong''s Limited');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('03230275', 'Wei Industrial Company Limited');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('00562454', 'Ziyi Toy Company Limited');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('03518649', 'Kazuma Technology Corporation');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('01238488', 'Mason Brothers Inc.');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('01883220', 'Liao Kee Network Systems Limited');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('05876198', 'Philip Consultants LLC');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('02374178', 'Kono Network Systems Corporation');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('04306757', 'Hiu Tung Communications Limited');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('00496544', 'Matsui Corporation');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('08293954', 'Beverly Logistic Inc.');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('08398888', 'Tsz Ching Network Systems Limited');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('08696762', 'Long Kee Company Limited');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('08730480', 'Ayano Residence Corporation');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('00299022', 'Sugawara Toy Corporation');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('09215559', 'Ayano Corporation');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('08978837', 'Momoe Food Corporation');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('01459968', 'Hikaru Corporation');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('03190241', 'Lopez Network Systems LLC');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('08961983', 'Shibata Network Systems Corporation');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('01703832', 'Christopher LLC');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('08184443', 'Hana Corporation');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('05014613', 'Cook Brothers Inc.');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('06244217', 'Hina Food Corporation');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('09831704', 'Jialun Property Company Limited');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('02966915', 'Miu Corporation');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('00603232', 'Dai Development & Trading Company Limited');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('08723239', 'Jialun Food Company Limited');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('07278983', 'Tse Kee Technology Limited');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('02099446', 'Rui Company Limited');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('02806945', 'Koon Kee Limited');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('02831565', 'Kwok Yin Communications Limited');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('06985073', 'Nomura Corporation');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('02068244', 'Momoe Pharmaceutical Corporation');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('00634830', 'Kwok Wing Limited');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('09751736', 'Ma Kee Company Limited');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('05354139', 'Tracy Trading Inc.');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('01885248', 'Tin Wing Limited');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('09290587', 'Mui Kee Property Limited');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('04301592', 'Xiuying Company Limited');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('05556243', 'Mitsuki Corporation');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('03260159', 'Ashley Inc.');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('05337804', 'Au''s Limited');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('04281740', 'Murata Residence Corporation');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('07161957', 'To''s Food Limited');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('04748885', 'Fu Shing Limited');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('03372548', 'Chieh Lun Limited');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('09385733', 'Black Consultants LLC');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('09871632', 'Mitchell Communications Inc.');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('04948476', 'Yin''s Limited');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('09716445', 'Johnson Brothers Pharmaceutical LLC');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('03818336', 'Wing Kuen Toy Limited');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('07308901', 'Shino Electronic Corporation');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('05073566', 'Sara Corporation');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('00164085', 'Su Kee Pharmaceutical Company Limited');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('08250841', 'Lu Technology Company Limited');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('02908403', 'Dai Company Limited');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('09295117', 'Reyes Brothers LLC');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('06164324', 'Chu Kee Limited');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('02621319', 'Zhang Consultants Company Limited');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('08271624', 'Jialun Company Limited');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('01655827', 'Cai Kee Communications Company Limited');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('00394703', 'Hikari Corporation');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('07378119', 'Chu Kee Electronic Limited');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('06181604', 'Anqi Company Limited');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('05461523', 'Miu Communications Corporation');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('03703663', 'Zhiyuan Telecommunication Company Limited');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('07489792', 'Wai Lam Limited');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('01127942', 'Jeffery Network Systems Inc.');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('06596743', 'Yuning Telecommunication Company Limited');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('08279156', 'Hikaru Network Systems Corporation');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('03567470', 'Heung''s Limited');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('01657128', 'Kathryn Technology LLC');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('05031252', 'Ng Kee Logistic Limited');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('03090534', 'Ethel LLC');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('02933665', 'Lai Yan Limited');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('06924669', 'Chi Yuen Limited');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('08307545', 'Mio Toy Corporation');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('00729314', 'Anqi Company Limited');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('01982978', 'Shino Corporation');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('04258599', 'Hok Yau Electronic Limited');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('02527338', 'Parker LLC');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('03093047', 'Ho Yin Limited');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('03737767', 'Wood Brothers Logistic LLC');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('09011984', 'Momoe Residence Corporation');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('06560928', 'Garcia''s Engineering LLC');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('03854204', 'Riku Food Corporation');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('02446677', 'Tamura Corporation');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('08801203', 'Wan''s Electronic Limited');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('05356218', 'Ford LLC');
INSERT INTO "customer_company" ("identifier", "title") VALUES ('00293334', 'Yan Kee Technology Company Limited');


INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('closed', '796.29', 2, 'AE-AD-0790-U');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('suspended', '749.03', 36, 'AC-EA-3882-P');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('active', '91.68', 48, 'BC-EA-5527-M');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('active', '575.35', 39, 'FA-FF-6005-Z');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('suspended', '18.58', 5, 'FB-CA-1965-B');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('active', '299.96', 13, 'BA-CD-6140-O');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('active', '763.77', 3, 'BF-CD-7386-C');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('active', '621.58', 68, 'EB-BF-0665-J');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('active', '36.77', 43, 'FA-AC-7628-V');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('closed', '992.02', 53, 'FF-BF-8720-R');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('suspended', '432.83', 13, 'ED-EC-0242-G');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('suspended', '454.80', 86, 'AD-FF-3812-J');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('closed', '731.12', 4, 'AB-DE-4082-B');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('closed', '0.82', 68, 'BE-DD-1732-H');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('closed', '666.19', 95, 'CC-CC-4766-C');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('suspended', '14.63', 68, 'AF-FB-9593-Y');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('active', '725.99', 58, 'DC-FE-9788-K');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('closed', '907.19', 75, 'FA-EF-3305-Q');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('suspended', '727.20', 35, 'CE-FB-9195-Y');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('closed', '336.86', 4, 'FF-BD-2658-L');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('active', '903.17', 21, 'EF-DD-0608-O');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('suspended', '134.26', 76, 'BE-BA-2319-D');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('active', '610.24', 16, 'BC-BA-8667-E');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('active', '917.81', 7, 'BE-BC-4664-T');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('active', '925.10', 48, 'DC-AA-9174-J');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('active', '868.61', 8, 'DA-CD-2602-V');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('suspended', '952.63', 54, 'FE-AB-1949-S');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('closed', '801.01', 4, 'EE-AC-4901-N');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('suspended', '84.08', 11, 'EC-EE-7956-C');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('suspended', '237.93', 53, 'CC-AA-5806-E');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('suspended', '299.63', 98, 'CD-DB-8344-R');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('active', '453.39', 8, 'DC-CD-9395-E');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('closed', '207.96', 99, 'EB-AB-3405-S');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('suspended', '317.16', 36, 'DE-CC-1181-O');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('suspended', '448.48', 6, 'AE-FB-0665-D');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('active', '424.76', 40, 'BD-CB-1922-Y');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('suspended', '559.74', 55, 'BD-AD-2695-P');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('active', '676.15', 91, 'EB-EE-5445-V');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('closed', '972.36', 48, 'CB-DF-9317-P');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('active', '502.40', 27, 'DB-CA-4992-Y');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('suspended', '24.69', 41, 'AE-CA-4445-D');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('suspended', '412.16', 45, 'AA-AB-4588-Y');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('closed', '254.06', 18, 'BC-AD-5917-Q');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('suspended', '0.54', 48, 'CC-DA-4677-F');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('active', '599.74', 64, 'FF-ED-0348-S');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('active', '277.44', 58, 'ED-CA-0138-I');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('closed', '995.68', 6, 'EF-AD-8082-E');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('suspended', '885.10', 48, 'FE-CC-6362-J');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('closed', '903.34', 89, 'EE-DE-1837-T');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('active', '320.45', 72, 'FF-FA-8855-A');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('closed', '17.69', 33, 'FF-BC-3777-L');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('closed', '399.67', 49, 'AC-DF-1380-G');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('suspended', '212.71', 82, 'DD-AF-4132-G');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('suspended', '499.27', 75, 'CE-FF-9281-G');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('suspended', '884.90', 11, 'BF-BA-9170-Y');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('active', '997.05', 70, 'DE-CF-6696-Y');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('suspended', '378.72', 47, 'CA-FE-6250-G');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('suspended', '764.18', 22, 'CE-BE-6795-V');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('active', '296.32', 94, 'CE-BF-1462-P');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('closed', '828.15', 65, 'AA-CF-3149-E');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('closed', '2.85', 51, 'DB-CE-0723-Y');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('closed', '295.76', 90, 'AA-CD-9786-R');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('active', '468.47', 7, 'ED-FB-9878-U');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('closed', '253.60', 23, 'CD-CF-0806-V');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('suspended', '857.84', 30, 'CD-CF-0995-N');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('active', '961.93', 66, 'FC-DF-2097-B');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('active', '308.21', 89, 'FC-CC-5906-Z');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('suspended', '737.47', 55, 'DF-BF-8059-G');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('closed', '263.02', 17, 'DB-BF-4565-V');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('closed', '767.03', 20, 'AB-DA-8935-S');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('active', '128.06', 35, 'DA-DA-3422-U');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('closed', '511.22', 82, 'BD-DB-3899-G');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('active', '987.44', 11, 'DC-DF-3930-I');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('suspended', '535.20', 9, 'BF-EF-5771-A');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('suspended', '659.56', 77, 'EB-AF-0615-P');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('suspended', '827.23', 41, 'CE-EF-0505-N');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('suspended', '974.87', 58, 'BA-AB-3748-U');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('active', '317.48', 12, 'BA-FA-3702-A');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('active', '455.12', 30, 'AB-DA-1079-C');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('active', '127.45', 69, 'CA-DA-7371-L');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('closed', '256.51', 35, 'EB-FD-3641-W');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('active', '226.69', 89, 'DD-EC-1961-B');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('suspended', '763.24', 42, 'FA-AD-8875-B');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('suspended', '718.14', 52, 'DC-FC-5255-X');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('active', '636.60', 59, 'BC-CA-4170-K');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('suspended', '373.17', 20, 'CA-DD-3083-O');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('closed', '324.94', 4, 'AB-AA-2375-Z');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('suspended', '659.45', 63, 'EB-BF-5228-S');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('suspended', '681.10', 18, 'EC-FC-7804-X');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('active', '576.75', 45, 'DD-CA-8478-C');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('active', '502.11', 22, 'BA-FD-5093-A');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('suspended', '418.53', 21, 'CC-FC-5146-L');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('active', '108.33', 4, 'FF-DD-0318-C');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('active', '990.52', 70, 'AA-CC-1309-P');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('closed', '323.71', 37, 'DC-AE-0603-C');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('active', '127.95', 69, 'FC-DD-4294-V');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('suspended', '803.33', 65, 'CE-DD-0081-I');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('active', '883.59', 54, 'AD-ED-8136-Q');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('suspended', '2.25', 18, 'DC-FF-0243-R');
INSERT INTO "account" ("status", "balance", "customer_id", "bank_identifier") VALUES ('active', '530.80', 23, 'BF-AA-4562-A');
